# Site settings
name: testall
email: testall0836@gmail.com
author: 김동근
url: https://testall0836.github.io
resume_site: https://github.com/testall0836/
github: https://github.com/testall0836/
baseurl:
description: Actually, less is more!
meta_description: 반갑습니다.
motto: It's our wits that make us men.
banner: 테스트1，테스트2

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: testall0836

# Build settings
markdown: kramdown